(function(){
const courses=window.HH_COURSES||[];const bundles=window.HH_COURSE_BUNDLES=window.HH_COURSE_BUNDLES||{};
let currentCourse=null,currentPath=null;const $=s=>document.querySelector(s);
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function fmtStatus(s){return (s||'').replaceAll('_',' ').toLowerCase().replace(/\b\w/g,m=>m.toUpperCase());}
async function ensureCourse(slug){return courses.find(x=>x.slug===slug)||null;}
function courseCard(c){const mins=c.estimated_minutes?`<span>${(c.estimated_minutes/60).toFixed(1)} hrs est.</span>`:'';return `<article class="course-card" data-search="${esc((c.title+' '+c.category).toLowerCase())}"><div class="cover-fallback"><span>H&amp;H</span><b>${esc(c.category)}</b></div><div class="course-body"><div class="ey">${esc(c.category)}</div><h3>${esc(c.title)}</h3><div class="metrics"><span>${c.lesson_count} lessons/topics</span><span>${c.assessment_count} assessment/practice</span>${mins}<span>${c.asset_count} learner pages</span></div><p class="status">${esc(fmtStatus(c.source_status))}</p><a class="btn" href="/academy/student.html?course=${encodeURIComponent(c.slug)}">Open course</a></div></article>`}
function renderCatalog(){let groups={};courses.forEach(c=>(groups[c.category]??=[]).push(c));$('#catalog').classList.remove('loading');$('#catalog').innerHTML=Object.entries(groups).map(([g,arr])=>`<section class="catalog-group"><h2>${esc(g)}</h2><div class="course-grid">${arr.map(courseCard).join('')}</div></section>`).join('');let q=$('#academySearch');if(q)q.oninput=()=>{let term=q.value.trim().toLowerCase();document.querySelectorAll('.course-card').forEach(card=>card.hidden=!!term&&!card.dataset.search.includes(term));document.querySelectorAll('.catalog-group').forEach(group=>group.hidden=!Array.from(group.querySelectorAll('.course-card')).some(c=>!c.hidden));};}
function renderCourse(c){currentCourse=c.slug;let recs=bundles[c.slug]||[];let cats={};recs.forEach(r=>(cats[r.category]??=[]).push(r));$('#courseView').innerHTML=`<div class="breadcrumbs"><a href="/academy/student.html">Student Academy</a> / ${esc(c.title)}</div><section class="course-hero"><div><div class="ey">${esc(c.category)} · ${esc(fmtStatus(c.source_status))}</div><h1>${esc(c.title)}</h1><p>${c.lesson_count} lessons/topics · ${c.assessment_count} assessment/practice records · ${c.asset_count} learner pages loaded</p><div class="metric-pills">${c.module_count?`<span>${c.module_count} modules</span>`:''}<span>${c.lesson_count} lessons</span><span>${c.assessment_count} assessments/practice</span>${c.estimated_minutes?`<span>${(c.estimated_minutes/60).toFixed(1)} estimated hours</span>`:''}</div><button class="btn gold" data-open-first>Start / Continue</button></div><div class="course-hero-fallback">HARBOR &amp; HIVE<br><small>${esc(c.category)}</small></div></section><label for="assetSearch"><b>Find material in this track</b></label><br><input id="assetSearch" class="searchbox" type="search" placeholder="Search lesson, workbook, case, workpaper, job aid…"><div class="asset-groups">${Object.entries(cats).map(([cat,rs])=>`<section class="asset-group"><h2>${esc(cat)} <small>${rs.length}</small></h2><div class="asset-grid">${rs.map(r=>`<button class="asset-card" data-path="${esc(r.path)}" data-search="${esc((r.title+' '+cat).toLowerCase())}"><b>${esc(r.title)}</b><span>${esc(r.kind.toUpperCase())}</span></button>`).join('')}</div></section>`).join('')}</div>`;
$('#courseView').querySelectorAll('[data-path]').forEach(b=>b.onclick=()=>openAsset(c.slug,b.dataset.path));let first=recs.find(r=>r.category==='Course Overview')||recs[0];let start=$('[data-open-first]');if(start&&first)start.onclick=()=>openAsset(c.slug,first.path);let q=$('#assetSearch');if(q)q.oninput=()=>{let term=q.value.trim().toLowerCase();document.querySelectorAll('.asset-card').forEach(card=>card.hidden=!!term&&!card.dataset.search.includes(term));document.querySelectorAll('.asset-group').forEach(group=>group.hidden=!Array.from(group.querySelectorAll('.asset-card')).some(x=>!x.hidden));};document.title=c.title+' | Harbor & Hive Tax Academy';}
function readerToolbar(){return `<div class="reader-tools"><button onclick="hhBackToCourse()">← Course</button><button onclick="hhSaveDraft()">Save Draft</button><button onclick="hhResumeDraft()">Resume Saved</button><button onclick="hhExportDraft()">Export Work</button><button onclick="hhPrintAsset()">Print</button><span id="saveState" aria-live="polite"></span></div>`;}
function resolveInternalPath(basePath,href){try{return new URL(href,'https://academy.local/'+basePath).pathname.replace(/^\//,'');}catch(e){return null;}}
function wireFrameLinks(frame,slug,rec){let d=frame.contentDocument;if(!d)return;d.addEventListener('click',e=>{let a=e.target.closest&&e.target.closest('a[href]');if(!a)return;let raw=(a.getAttribute('href')||'').trim();if(!raw||raw.startsWith('#'))return;if(/^(https?:|mailto:|tel:|javascript:)/i.test(raw)){if(/^https?:/i.test(raw)){a.target='_blank';a.rel='noopener noreferrer';}return;}let target=resolveInternalPath(rec.path,raw);if(target&&(bundles[slug]||[]).some(r=>r.path===target)){e.preventDefault();openAsset(slug,target);}});}
window.hhOpenAsset=async function(slug,path){await ensureCourse(slug);openAsset(slug,path)};
function openAsset(slug,path){let rec=(bundles[slug]||[]).find(r=>r.path===path);if(!rec)return;currentCourse=slug;currentPath=path;$('#reader').innerHTML=readerToolbar()+`<iframe id="assetFrame" title="${esc(rec.title)}"></iframe>`;$('#reader').classList.add('open');document.body.classList.add('reading');let f=$('#assetFrame');f.srcdoc=rec.html;f.onload=()=>{wireFrameLinks(f,slug,rec);restoreDraft(true);};history.replaceState({},'',`/academy/student.html?course=${encodeURIComponent(slug)}&asset=${encodeURIComponent(path)}`);}
window.hhBackToCourse=function(){$('#reader').classList.remove('open');document.body.classList.remove('reading');let c=courses.find(x=>x.slug===currentCourse);if(c){history.replaceState({},'',`/academy/student.html?course=${encodeURIComponent(c.slug)}`);renderCourse(c)}};
function controls(){let f=$('#assetFrame');if(!f||!f.contentDocument)return[];return Array.from(f.contentDocument.querySelectorAll('textarea,input:not([type=button]):not([type=submit]),select'))}
function key(){return 'hhacademy:v1.1:'+currentPath}
function snapshot(){let vals=controls().map((el,i)=>({i,name:el.name||'',id:el.id||'',type:el.type||el.tagName.toLowerCase(),value:(el.type==='checkbox'||el.type==='radio')?el.checked:el.value}));return {course:currentCourse,path:currentPath,saved_at:new Date().toISOString(),values:vals}}
window.hhSaveDraft=function(){if(!currentPath)return;localStorage.setItem(key(),JSON.stringify(snapshot()));$('#saveState').textContent='Saved '+new Date().toLocaleTimeString();}
function restoreDraft(silent=false){if(!currentPath)return;let raw=localStorage.getItem(key());if(!raw){if(!silent)$('#saveState').textContent='No saved draft for this asset.';return}try{let d=JSON.parse(raw),els=controls();d.values.forEach(v=>{let el=els[v.i];if(!el)return;if(el.type==='checkbox'||el.type==='radio')el.checked=!!v.value;else el.value=v.value});if(!silent)$('#saveState').textContent='Saved work restored.'}catch(e){if(!silent)$('#saveState').textContent='Could not restore draft.'}}
window.hhResumeDraft=()=>restoreDraft(false);
window.hhExportDraft=function(){let d=snapshot();let blob=new Blob([JSON.stringify(d,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(currentCourse||'academy')+'-'+(currentPath||'work').split('/').pop().replace(/\.[^.]+$/,'')+'-student-work.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
window.hhPrintAsset=function(){let f=$('#assetFrame');if(f)f.contentWindow.print()}
async function boot(){if(!courses.length){$('#catalog').textContent='Academy curriculum could not be loaded.';return}renderCatalog();let q=new URLSearchParams(location.search),slug=q.get('course'),asset=q.get('asset');if(slug){let c=await ensureCourse(slug);if(c){$('#homeView').hidden=true;$('#courseView').hidden=false;renderCourse(c);if(asset)setTimeout(()=>openAsset(slug,asset),0)}}else{$('#homeView').hidden=false;$('#courseView').hidden=true}}
window.addEventListener('popstate',()=>location.reload());boot();
})();
